$(function() {
    $(".owl-carousel").owlCarousel({
        loop:true,
        rtl:true,
        nav:false,
        dots:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:4
            }
        }
    });
});